### ISSUE TITLE
jquery__ui: зависимость от jquery

### ISSUE THREAD

**Issue by remnev** [factorymn/bem-factory#6]
Пытался подключить jquery__ui, но не получается. После загрузки скрипта с CDN он выполняется и кидает ошибку в месте, где пытается прочитать window.jQuery.
Я не понял как подразумевалось это должно было работать, если jQuery провайдится модулем и в глобальном скойпе этого имени нет?

**Comment by voischev** [comment]
наверное это работало когда jquery мы подключали в head по старинке

**Comment by remnev** [comment]
А есть идеи как можно их подружить?

**Comment by remnev** [comment]
А примешь примерно такой код:
```js
modules.define(
    'jquery__ui',
    ['loader_type_js', 'jquery'],
    function(provide, loader, $) {
        window.jQuery = window.$ = $;
        typeof $.ui !== 'undefined'?
            provide($.ui) :
            loader(
                '//yastatic.net/jquery-ui/1.11.1/jquery-ui.min.js',
                function() {
                    delete window.jQuery;
                    delete window.$;
                    provide($.ui);
                });
});

```

?
